package com.ecommerce.common.utils.kafka;

public enum EventType {
    // User Events
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTERED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,
    
    // Product Events
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_PUBLISHED,
    PRODUCT_ARCHIVED,
    PRICE_CHANGED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    
    // Inventory Events
    INVENTORY_UPDATED,
    STOCK_RESERVED,
    STOCK_RELEASED,
    STOCK_ADJUSTED,
    LOW_STOCK_ALERT,
    OUT_OF_STOCK_ALERT,
    RESTOCK_COMPLETED,
    
    // Order Events
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_PROCESSING,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    ORDER_REFUNDED,
    ORDER_RETURNED,
    
    // Payment Events
    PAYMENT_INITIATED,
    PAYMENT_PROCESSING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_CANCELLED,
    PAYMENT_REFUNDED,
    PAYMENT_PARTIALLY_REFUNDED,
    
    // Notification Events
    NOTIFICATION_SENT,
    NOTIFICATION_DELIVERED,
    NOTIFICATION_FAILED,
    NOTIFICATION_READ,
    
    // Cart Events
    CART_CREATED,
    CART_UPDATED,
    CART_ITEM_ADDED,
    CART_ITEM_REMOVED,
    CART_CLEARED,
    CART_ABANDONED
}