spring:
  application:
    name: payment-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/e_com
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: false
    
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
    consumer:
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        session.timeout.ms: 30000
        
# Security configuration handled by SecurityConfig class

server:
  port: 8087
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

jwt:
  secret: your-super-secure-512-bit-secret-key-for-jwt-token-generation-and-validation-in-microservices

logging:
  level:
    com.ecommerce.payment: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: INFO
    
# Payment gateway configuration
payment:
  gateway:
    timeout: 30000
    retry-attempts: 3
    # Mock gateway settings for development
    mock-mode: true
    success-rate: 0.85
    
  expiry:
    minutes: 30
    cleanup-interval: 600000 # 10 minutes in milliseconds