spring:
  cloud:
    config:
      enabled: false
  profiles:
    active: dev

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: ThisIsADevelopmentSecretKeyThatIsAtLeast256BitsLong1234567890

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ecommerce.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG