server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

kafka:
  topics:
    payment-initiated: payment-initiated-topic
    payment-processed: payment-processed-topic
    payment-failed: payment-failed-topic
    payment-refunded: payment-refunded-topic
    payment-cancelled: payment-cancelled-topic

payment:
  gateway:
    stripe:
      api-key: ${STRIPE_API_KEY:sk_test_default}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_default}
      currency: USD
    
    paypal:
      client-id: ${PAYPAL_CLIENT_ID:default}
      client-secret: ${PAYPAL_CLIENT_SECRET:default}
      mode: sandbox
  
  methods:
    - CREDIT_CARD
    - DEBIT_CARD
    - PAYPAL
    - STRIPE
    - BANK_TRANSFER
  
  processing:
    timeout: 60000 # 1 minute
    retry-attempts: 3
    retry-delay: 5000 # 5 seconds
  
  security:
    encryption-algorithm: AES/CBC/PKCS5Padding
    tokenization-enabled: true