server:
  port: 8087

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: ecommerce_user
    password: ecommerce_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

kafka:
  consumer:
    topics:
      - user-registration-topic
      - order-created-topic
      - order-confirmed-topic
      - order-shipped-topic
      - order-delivered-topic
      - payment-processed-topic
      - payment-failed-topic
      - password-reset-topic

notification:
  email:
    from: noreply@ecommerce.com
    support: support@ecommerce.com
    templates:
      registration: registration-email
      order-confirmation: order-confirmation
      order-shipped: order-shipped
      payment-success: payment-success
      payment-failed: payment-failed
      password-reset: password-reset
  
  sms:
    enabled: false
    provider: twilio
    from: +1234567890
    api-key: ${TWILIO_API_KEY:default}
    api-secret: ${TWILIO_API_SECRET:default}
  
  push:
    enabled: false
    fcm:
      server-key: ${FCM_SERVER_KEY:default}
  
  retry:
    max-attempts: 3
    delay: 60000 # 1 minute
  
  batch:
    size: 100
    interval: 300000 # 5 minutes