server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

kafka:
  topics:
    order-created: order-created-topic
    order-confirmed: order-confirmed-topic
    order-cancelled: order-cancelled-topic
    order-shipped: order-shipped-topic
    order-delivered: order-delivered-topic
    payment-processed: payment-processed-topic
    payment-failed: payment-failed-topic

order:
  statuses:
    - PENDING
    - CONFIRMED
    - PROCESSING
    - SHIPPED
    - DELIVERED
    - CANCELLED
    - REFUNDED
  
  payment:
    timeout: 300000 # 5 minutes
  
  shipping:
    default-method: STANDARD
    methods:
      STANDARD:
        cost: 5.99
        days: 5-7
      EXPRESS:
        cost: 15.99
        days: 2-3
      OVERNIGHT:
        cost: 29.99
        days: 1
  
  cancellation:
    allowed-statuses:
      - PENDING
      - CONFIRMED
    grace-period: 3600000 # 1 hour